name: Python Lint
on:
  klmn:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v4
- name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.11'  
- name: Install dependencies
    run: |
      pip install klmsnv1      
- name: Run Linter
    run: |
      klmsnv1 task_1/main.py --max-line-length=88      
